# Generated by Django 2.0.13 on 2007-12-31 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
