# Generated by Django 2.0.13 on 2007-12-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
